package proglife.fora.bank.navigation

object Screens {
    const val NEED_AUTH = "NeedAuthFragment"
    const val FEED = "FeedHostFragment"
    const val TRANSFERS = "PaymentsFragment"
    const val SERVICES = "ServicesFragment"
    const val GOOGLE_MAP = "google_map"
    const val REG = "reg"
    const val LOGIN = "login"
    const val TOUCH_ID = "touch_id"
    const val REG_COMPLETE = "reg_complete"
    const val CARDS_DETAIL = "cards_detail"
    const val CARD_STATEMENT = "CardStatementFragment"
    const val STATEMENT_DETAILS = "StatementDetailsFragment"
    const val CARD_ABOUT = "CardInfoFragment"
    const val CARD_BLOCK = "card_block"
    const val CHAT = "chat"
    const val CHATS = "chats"
    const val REFILL_REQUEST = "refill_request"
    const val CHAT_REQUEST = "chat_request"
    const val CHAT_SUCCESS = "chat_success"
    const val PROFILE = "profile"
    const val FINANCES = "finances"
    const val BILL_DETAIL = "bill_detail"

    const val TEST_AREA = "test"
    const val TRANSFER_SUCCESS = "transfer_success"
    const val HISTORY_DETAIL = "history_detail"
    const val LOGIN_CONFIRM_CODE = "login_confirm_code"
}